import Head from 'next/head'
import { About, Header, Navbar, Skills, Work } from '../components'



export default function Home() {
  return (
    <div className=" bg-[#edf2f8] font-[DM Sans,sans-serif]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="">
        <Navbar />
        <Header/>
        <About/> 
        <Work/>
        <Skills/>
        
      </div>

       

    </div>
  )
}
